# Site Configuration - cocoonspamini.com
title: Cocoon Spamini
description: Blog about cocoons and insects
url: https://cocoonspamini.com
baseurl: ""

# Author information
author:
  name: Your Name
  email: your@email.com

# Jekyll configuration
timezone: UTC
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build configuration
destination: ../_site/cocoonspamini

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

