---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart container-health-monitor
  systemd:
    name: container-health-monitor
    state: restarted
    daemon_reload: yes

