---
- name: Smart Deploy Services Container
  hosts: services_container_hosts
  become: yes
  tasks:
    - name: Get local container image ID
      ansible.builtin.shell: |
        docker images rl337/callableapis:services -q 2>/dev/null || echo ""
      register: local_image_id
      changed_when: false
      failed_when: false

    - name: Pull latest services container image
      ansible.builtin.command: docker pull rl337/callableapis:services
      register: pull_result
      failed_when: false
      changed_when: "'Downloaded newer image' in pull_result.stdout or 'Pulling from' in pull_result.stdout"

    - name: Get new container image ID
      ansible.builtin.shell: |
        docker images rl337/callableapis:services -q
      register: new_image_id
      when: pull_result.changed
      changed_when: false

    - name: Check if image actually changed
      ansible.builtin.set_fact:
        image_changed: "{{ new_image_id.stdout != local_image_id.stdout }}"
      when: pull_result.changed and local_image_id.stdout != ""
      failed_when: false

    - name: Set default image_changed to true if no local image exists
      ansible.builtin.set_fact:
        image_changed: true
      when: local_image_id.stdout == ""

    - name: Check if container is running
      ansible.builtin.shell: docker ps --filter name=callableapis-services -q
      register: container_check
      changed_when: false
      failed_when: false

    - name: Stop existing services container
      ansible.builtin.shell: |
        docker stop callableapis-services
        docker rm callableapis-services
      when: image_changed | default(false) and container_check.rc == 0
      failed_when: false

    - name: Deploy services container with vault mount
      ansible.builtin.shell: |
        docker run -d \
          --name callableapis-services \
          --restart unless-stopped \
          -p {{ services_port | default('8080') }}:8080 \
          -v /home/ansible/.ansible/vault:/app/vault:ro \
          rl337/callableapis:services
      register: container_deploy
      when: image_changed | default(false)
      failed_when: false

    - name: Wait for container to be ready
      ansible.builtin.wait_for:
        port: "{{ services_port | default('8080') }}"
        host: "127.0.0.1"
        timeout: 30
      when: image_changed | default(false) and container_deploy.rc == 0

    - name: Verify services container is running
      ansible.builtin.shell: docker ps --filter name=callableapis-services
      register: container_status
      when: image_changed | default(false)
      changed_when: false

    - name: Display deployment status
      ansible.builtin.debug:
        msg: |
          Services Container Status:
          - Local Image ID: {{ local_image_id.stdout | default('None') }}
          - New Image ID: {{ new_image_id.stdout | default('None') }}
          - Image Changed: {{ image_changed | default(false) }}
          - Container Deployed: {{ container_deploy.changed | default(false) if container_deploy is defined else False }}
          - Pull Result: {{ pull_result.stdout_lines[-1] if pull_result.stdout_lines else 'No output' }}