# Encrypted secrets for CallableAPIs infrastructure
# This file is encrypted with Ansible Vault
# To edit: ansible-vault edit group_vars/secrets.yml
# To view: ansible-vault view group_vars/secrets.yml

# GitHub OIDC Configuration (only secrets deployed to containers)
github_client_id: "{{ vault_github_client_id }}"
github_client_secret: "{{ vault_github_client_secret }}"
github_redirect_uri: "{{ vault_github_redirect_uri }}"
