---
- name: Build CallableAPIs Secrets
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    artifacts_dir: "{{ playbook_dir }}/../artifacts"
    vault_password_file: "{{ artifacts_dir }}/vault-password"
    secrets_file: "{{ artifacts_dir }}/secrets.yml"

  tasks:
    - name: Create artifacts directory
      file:
        path: "{{ artifacts_dir }}"
        state: directory
        mode: "0700"

    - name: Generate vault password
      shell: openssl rand -base64 32
      register: vault_password
      changed_when: false

    - name: Save vault password to file
      copy:
        content: "{{ vault_password.stdout }}"
        dest: "{{ vault_password_file }}"
        mode: "0600"

    - name: Create secrets file
      copy:
        content: |
          # CallableAPIs Infrastructure Secrets
          # Generated on {{ ansible_date_time.iso8601 }}
          # Only GitHub OIDC secrets are deployed to containers
          # All other credentials are managed locally in env.sh

          # GitHub OIDC Configuration
          vault_github_client_id: "{{ github_client_id | default('') }}"
          vault_github_client_secret: "{{ github_client_secret | default('') }}"
          vault_github_redirect_uri: "{{ github_redirect_uri | default('https://api.callableapis.com/api/auth/callback') }}"
        dest: "{{ secrets_file }}"
        mode: "0600"

    - name: Encrypt secrets file
      shell: ansible-vault encrypt "{{ secrets_file }}" --vault-password-file "{{ vault_password_file }}"
      when: github_client_id is defined and github_client_id != ""

    - name: Generate vault password checksum
      shell: sha256sum "{{ vault_password_file }}" > "{{ vault_password_file }}.sha256"
      when: github_client_id is defined and github_client_id != ""

    - name: Generate secrets file checksum
      shell: sha256sum "{{ secrets_file }}" > "{{ secrets_file }}.sha256"
      when: github_client_id is defined and github_client_id != ""

    - name: Display summary
      debug:
        msg: |
          Secrets built successfully!

          Files created in {{ artifacts_dir }}:
            - vault-password (vault password file)
            - secrets.yml (encrypted secrets)
            - vault-password.sha256 (checksum)
            - secrets.yml.sha256 (checksum)

          Next steps:
            1. Deploy secrets: ansible-playbook -i inventory/production playbooks/deploy-secrets.yml
            2. Deploy container: ansible-playbook -i inventory/production playbooks/api-deploy.yml
      when: github_client_id is defined and github_client_id != ""

    - name: Display error if no credentials provided
      debug:
        msg: |
          Error: No GitHub OIDC credentials provided!

          Set environment variables:
            export GITHUB_CLIENT_ID="your_client_id"
            export GITHUB_CLIENT_SECRET="your_client_secret"
            export GITHUB_REDIRECT_URI="https://api.callableapis.com/api/auth/callback"

          Or run with:
            ansible-playbook -i inventory/production playbooks/build-secrets.yml -e "github_client_id=xxx github_client_secret=yyy"
      when: github_client_id is not defined or github_client_id == ""
