---
- name: Deploy Applications
  hosts: localhost
  become: no
  vars:
    playbook_dir: "{{ playbook_dir }}"

  tasks:
    - name: Deploy containers based on inventory groups
      ansible.builtin.import_playbook: containers/deploy-containers.yml

    - name: Configure dynamic Nginx routing
      ansible.builtin.import_playbook: nginx/setup-nginx.yml

    - name: Test application endpoints
      ansible.builtin.import_playbook: testing/test-endpoints.yml

    - name: Display deployment results
      ansible.builtin.debug:
        msg: |
          Application Deployment Complete
          - Containers deployed based on inventory groups
          - Nginx routing configured dynamically
          - Endpoints tested and verified
          Status: APPLICATIONS RUNNING
