---
- name: Deploy SSL certificates to all nodes
  hosts: onode1,onode2,gnode1,inode1
  become: yes
  vars:
    ssl_cert_dir: "/etc/ssl/callableapis"
    nginx_ssl_dir: "/etc/nginx/ssl"
    artifacts_dir: "{{ playbook_dir }}/../artifacts"

  tasks:
    - name: Create SSL certificate directory
      ansible.builtin.file:
        path: "{{ ssl_cert_dir }}"
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Create Nginx SSL directory
      ansible.builtin.file:
        path: "{{ nginx_ssl_dir }}"
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Check current certificate files
      ansible.builtin.stat:
        path: "{{ ssl_cert_dir }}/{{ item }}"
      register: current_certs
      loop:
        - privkey.pem
        - cert.pem
        - fullchain.pem
        - chain.pem

    - name: Check if certificates need updating
      ansible.builtin.set_fact:
        certs_need_update: |
          {{
            current_certs.results | selectattr('stat.exists', 'equalto', false) | list | length > 0 or
            (current_certs.results | selectattr('stat.exists', 'equalto', true) | first | attr('stat') | attr('size') < 1500)
          }}

    - name: Copy private key from artifacts
      ansible.builtin.copy:
        src: "{{ artifacts_dir }}/ssl/privkey.pem"
        dest: "{{ ssl_cert_dir }}/privkey.pem"
        mode: "0600"
        owner: root
        group: root
        backup: yes
        remote_src: no
      when: certs_need_update

    - name: Copy certificate from artifacts
      ansible.builtin.copy:
        src: "{{ artifacts_dir }}/ssl/cert.pem"
        dest: "{{ ssl_cert_dir }}/cert.pem"
        mode: "0644"
        owner: root
        group: root
        backup: yes
        remote_src: no
      when: certs_need_update

    - name: Copy fullchain from artifacts
      ansible.builtin.copy:
        src: "{{ artifacts_dir }}/ssl/fullchain.pem"
        dest: "{{ ssl_cert_dir }}/fullchain.pem"
        mode: "0644"
        owner: root
        group: root
        backup: yes
        remote_src: no
      when: certs_need_update

    - name: Copy chain from artifacts
      ansible.builtin.copy:
        src: "{{ artifacts_dir }}/ssl/chain.pem"
        dest: "{{ ssl_cert_dir }}/chain.pem"
        mode: "0644"
        owner: root
        group: root
        backup: yes
        remote_src: no
      when: certs_need_update

    - name: Create symlinks for Nginx
      ansible.builtin.file:
        src: "{{ ssl_cert_dir }}/{{ item.src }}"
        dest: "{{ nginx_ssl_dir }}/{{ item.dest }}"
        state: link
        force: yes
      loop:
        - { src: "privkey.pem", dest: "privkey.pem" }
        - { src: "cert.pem", dest: "cert.pem" }
        - { src: "fullchain.pem", dest: "fullchain.pem" }
        - { src: "chain.pem", dest: "chain.pem" }

    - name: Display SSL certificate deployment results
      ansible.builtin.debug:
        msg: |
          SSL Certificate Deployment Results for {{ inventory_hostname }}:
          - SSL Directory: {{ ssl_cert_dir }}
          - Nginx SSL Directory: {{ nginx_ssl_dir }}
          - Update Required: {{ 'YES' if certs_need_update else 'NO' }}
          - Status: {{ 'UPDATED' if certs_need_update else 'UP TO DATE' }}
