---
- name: Deploy Services Containers to Services Container Hosts
  hosts: services_container_hosts
  become: yes
  vars:
    services_container_name: "callableapis-services"
    services_container_image: "docker.io/rl337/callableapis:services"
    services_container_port: 8080
    services_host_port: 8082  # Different port to avoid conflict with base container

  tasks:
    - name: Check if Docker is installed
      ansible.builtin.command: which docker
      register: docker_check
      changed_when: false
      ignore_errors: yes

    - name: Fail if Docker is not installed
      ansible.builtin.fail:
        msg: "Docker is not installed on {{ inventory_hostname }}. Please run install-docker-standard.yml first."
      when: docker_check.rc != 0

    - name: Start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Wait for Docker to be ready
      ansible.builtin.wait_for:
        port: 2376
        host: localhost
        timeout: 30
      ignore_errors: yes

    - name: Pull services container image
      ansible.builtin.docker_image:
        name: "{{ services_container_image }}"
        source: pull
        force_source: yes
      register: pull_result

    - name: Fail if image pull failed
      ansible.builtin.fail:
        msg: "Failed to pull services container image {{ services_container_image }}. Make sure the image exists in Docker Hub."
      when: pull_result.failed

    - name: Stop existing services container if running
      ansible.builtin.docker_container:
        name: "{{ services_container_name }}"
        state: stopped
      ignore_errors: yes

    - name: Remove existing services container if exists
      ansible.builtin.docker_container:
        name: "{{ services_container_name }}"
        state: absent
      ignore_errors: yes

    - name: Deploy services container
      ansible.builtin.docker_container:
        name: "{{ services_container_name }}"
        image: "{{ services_container_image }}"
        state: started
        restart_policy: "unless-stopped"
        ports:
          - "{{ services_host_port }}:{{ services_container_port }}"
        env:
          CONTAINER_VERSION: "{{ ansible_date_time.iso8601 }}"
        labels:
          app: "callableapis"
          service: "services"
          managed_by: "ansible"
          deployed_at: "{{ ansible_date_time.iso8601 }}"
      register: deploy_result

    - name: Wait for services container to start
      ansible.builtin.wait_for:
        port: "{{ services_host_port }}"
        host: localhost
        timeout: 30

    - name: Test services container health endpoint
      ansible.builtin.uri:
        url: "http://localhost:{{ services_host_port }}/health"
        method: GET
        status_code: 200
      register: health_check_result
      failed_when: false

    - name: Test services container status endpoint
      ansible.builtin.uri:
        url: "http://localhost:{{ services_host_port }}/api/status"
        method: GET
        status_code: 200
      register: status_check_result
      failed_when: false

    - name: Display services container deployment results
      ansible.builtin.debug:
        msg: |
          Services Container Deployment Results for {{ inventory_hostname }}:
          - Container: {{ services_container_name }}
          - Image: {{ services_container_image }}
          - Container Port: {{ services_container_port }}
          - Host Port: {{ services_host_port }}
          - Health endpoint: {{ 'PASSED' if health_check_result.status == 200 else 'FAILED' }}
          - Status endpoint: {{ 'PASSED' if status_check_result.status == 200 else 'FAILED' }}
          - Access URL: http://localhost:{{ services_host_port }}
