---
- name: Manage Secrets
  hosts: localhost
  become: no
  vars:
    playbook_dir: "{{ playbook_dir }}"

  tasks:
    - name: Build secrets locally
      ansible.builtin.import_playbook: secrets/build-secrets.yml

    - name: Deploy secrets to nodes
      ansible.builtin.import_playbook: secrets/deploy-secrets-simple.yml

    - name: Display secrets management results
      ansible.builtin.debug:
        msg: |
          Secrets Management Complete
          - Secrets built locally
          - Secrets deployed to nodes
          - All secrets managed
          Status: SECRETS READY
