---
- name: Complete Infrastructure Setup
  hosts: localhost
  become: no
  vars:
    playbook_dir: "{{ playbook_dir }}"

  tasks:
    - name: Setup SSL certificates and firewall rules
      ansible.builtin.import_playbook: manage-ssl.yml

    - name: Deploy containers to all nodes
      ansible.builtin.import_playbook: deploy-applications.yml

    - name: Test all endpoints
      ansible.builtin.import_playbook: testing/test-endpoints.yml

    - name: Display setup completion
      ansible.builtin.debug:
        msg: |
          Complete Infrastructure Setup Finished
          - SSL certificates deployed
          - Firewall rules configured
          - Containers deployed
          - Nginx configured
          - Endpoints tested
          Status: READY FOR PRODUCTION
