# Site Configuration
# This is a template - customize for each domain

title: Your Site Title
description: Your site description
url: https://yourdomain.com
baseurl: ""

# Author information
author:
  name: Your Name
  email: your@email.com

# Jekyll configuration
timezone: UTC
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build configuration for Cloudflare Pages
destination: _site

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore

# Collections (for blog posts)
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

