---
- name: Build fresh SSH keypair artifact
  hosts: localhost
  gather_facts: false
  vars:
    artifact_dir: "{{ playbook_dir | dirname | dirname | dirname }}/ansible/artifacts/ssh"
    key_name: callableapis_rotated
    private_key_path: "{{ artifact_dir }}/{{ key_name }}_private_key"
    public_key_path: "{{ artifact_dir }}/{{ key_name }}_public_key"
  tasks:
    - name: Ensure artifact directory exists
      ansible.builtin.file:
        path: "{{ artifact_dir }}"
        state: directory
        mode: '0700'

    - name: Generate new SSH keypair
      community.crypto.openssh_keypair:
        path: "{{ private_key_path }}"
        type: rsa
        size: 4096
        mode: '0600'
      register: keypair_result

    - name: Write public key file explicitly (idempotent)
      ansible.builtin.copy:
        content: "{{ keypair_result.public_key }}\n"
        dest: "{{ public_key_path }}"
        mode: '0644'

    - name: Show key artifact locations
      ansible.builtin.debug:
        msg: |
          Created SSH key artifact:
          - Private: {{ private_key_path }}
          - Public : {{ public_key_path }}
          Distribute the public key to hosts and update Terraform to reference it.


