name: Build and Push Base Container

on:
    push:
        branches: [main]
        paths: ["containers/base/**"]
    pull_request:
        branches: [main]
        paths: ["containers/base/**"]
    workflow_dispatch:

env:
    REGISTRY: docker.io
    IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/callableapis

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: |
                  type=ref,event=branch
                  type=ref,event=pr
                  type=sha,prefix={{branch}}-
                  type=raw,value=base,enable={{is_default_branch}}
                  type=raw,value=latest,enable={{is_default_branch}}

            - name: Generate container version
              run: |
                echo "${{ github.repository }}/${{ github.sha }}" > containers/base/CONTAINER_VERSION

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./containers/base
                  file: ./containers/base/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  platforms: linux/amd64

            - name: Generate deployment info
              run: |
                  echo "## Base Container Build Summary" >> $GITHUB_STEP_SUMMARY
                  echo "- **Registry**: ${{ env.REGISTRY }}" >> $GITHUB_STEP_SUMMARY
                  echo "- **Image**: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
                  echo "- **Tags**: ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
                  echo "- **Size**: ~256MB (Alpine Linux base)" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "### Base Container Features" >> $GITHUB_STEP_SUMMARY
                  echo "- Python 3.12 runtime with essential packages" >> $GITHUB_STEP_SUMMARY
                  echo "- Ansible Vault secrets management" >> $GITHUB_STEP_SUMMARY
                  echo "- Health check endpoints (/health, /status)" >> $GITHUB_STEP_SUMMARY
                  echo "- Non-root user (appuser) for security" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
                  echo "1. Use as base image for other services (agents, api, etc.)" >> $GITHUB_STEP_SUMMARY
                  echo "2. Deploy to nodes using Ansible" >> $GITHUB_STEP_SUMMARY
                  echo "3. Build service-specific containers on top of this base" >> $GITHUB_STEP_SUMMARY
